import { useEffect, useState } from 'react'
import { Button } from '@/components/ui/button'

const empty = { name: '', description: '', price: '', shipping: '5.00', sortOrder: '0', image: null }

export default function Admin() {
  const [auth, setAuth] = useState(null), [password, setPassword] = useState(''), [form, setForm] = useState(empty), [products, setProducts] = useState([]), [message, setMessage] = useState(''), [busy, setBusy] = useState(false)
  const load = async () => { const session = await fetch('/api/admin/session').then(r => r.json()); setAuth(session.authenticated); if (session.authenticated) { const result = await fetch('/api/admin/products').then(r => r.json()); setProducts(result.products || []) } }
  useEffect(() => { load() }, [])
  const login = async (event) => { event.preventDefault(); setMessage(''); const response = await fetch('/api/admin/session', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ password }) }); if (!response.ok) return setMessage('Incorrect password.'); setAuth(true); setPassword(''); load() }
  const save = async (event) => { event.preventDefault(); if (!form.image) return setMessage('Choose a product image.'); setBusy(true); setMessage('Saving your product…'); const reader = new FileReader(); reader.onload = async () => { const response = await fetch('/api/admin/products', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, imageData: reader.result }) }); const result = await response.json(); setBusy(false); if (!response.ok) return setMessage(result.error); setForm(empty); setMessage('Product saved. Checkout can be enabled later.'); setProducts([result.product, ...products]) }; reader.readAsDataURL(form.image) }
  if (auth === null) return <main className='grid min-h-screen place-items-center bg-slate-50 p-5'><p className='text-slate-500'>Loading…</p></main>
  if (!auth) return <main className='grid min-h-screen place-items-center bg-slate-50 p-5'><form onSubmit={login} className='w-full max-w-sm rounded-lg border border-slate-200 bg-white p-7 shadow-sm'><p className='eyebrow text-[#39715a]'>Private</p><h1 className='mt-2 font-grandCru text-4xl text-[#283b46]'>Shop admin</h1><label className='mt-7 block text-sm font-semibold text-slate-600'>Password<input type='password' value={password} onChange={e => setPassword(e.target.value)} className='mt-2 w-full rounded-md border border-slate-300 px-3 py-2.5 outline-none focus:border-[#39715a]' autoFocus /></label>{message && <p className='mt-3 text-sm text-red-700'>{message}</p>}<Button className='mt-5 w-full' type='submit'>Sign in</Button></form></main>
  return <main className='min-h-screen bg-slate-50 px-5 py-10 text-slate-700'><div className='mx-auto max-w-5xl'><div className='flex items-center justify-between'><div><p className='eyebrow text-[#39715a]'>Private</p><h1 className='mt-2 font-grandCru text-5xl text-[#283b46]'>Shop admin</h1></div><button onClick={async () => { await fetch('/api/admin/session', { method: 'DELETE' }); setAuth(false) }} className='text-sm font-semibold text-[#39715a] hover:underline'>Sign out</button></div><p className='mt-5 rounded-md bg-[#edf6ef] p-4 text-sm text-[#39715a]'>Demo mode is on. Products will show in the shop, but checkout stays disabled until Stripe is configured.</p><div className='mt-6 grid gap-8 lg:grid-cols-[1.1fr_.9fr]'><form onSubmit={save} className='rounded-lg border border-slate-200 bg-white p-6 shadow-sm'><h2 className='font-grandCru text-3xl text-[#283b46]'>Add a product</h2><div className='mt-5 grid gap-4 sm:grid-cols-2'>{[['name','Product name'],['price','Display price (USD)'],['shipping','Future shipping (USD)'],['sortOrder','Display order']].map(([key,label]) => <label key={key} className='text-sm font-semibold text-slate-600'>{label}<input required={key !== 'sortOrder'} type={key === 'name' ? 'text' : 'number'} min='0' step={key === 'sortOrder' ? '1' : '0.01'} value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })} className='mt-2 w-full rounded-md border border-slate-300 px-3 py-2.5 outline-none focus:border-[#39715a]' /></label>)}</div><label className='mt-4 block text-sm font-semibold text-slate-600'>Description<textarea required rows='4' value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} className='mt-2 w-full rounded-md border border-slate-300 px-3 py-2.5 outline-none focus:border-[#39715a]' /></label><label className='mt-4 block text-sm font-semibold text-slate-600'>Product image<input required type='file' accept='image/jpeg,image/png,image/webp' onChange={e => setForm({ ...form, image: e.target.files[0] })} className='mt-2 block w-full text-sm' /></label>{message && <p className='mt-4 text-sm text-slate-600'>{message}</p>}<Button className='mt-5 w-full' type='submit' disabled={busy}>{busy ? 'Saving…' : 'Save demo product'}</Button></form><section className='rounded-lg border border-slate-200 bg-white p-6 shadow-sm'><h2 className='font-grandCru text-3xl text-[#283b46]'>Current products</h2>{products.length ? <ul className='mt-5 divide-y divide-slate-100'>{products.map(p => <li key={p.id} className='py-4'><strong className='block text-[#283b46]'>{p.name}</strong><span className='text-sm text-slate-500'>${(p.price_cents / 100).toFixed(2)} · {p.stripe_payment_link ? 'Checkout ready' : 'Demo only'}</span></li>)}</ul> : <p className='mt-5 text-sm text-slate-500'>No products yet.</p>}</section></div></div></main>
}
